from board import Board, Track
from missions import *

def europe_board():
    b = Board("europe", 45)
    b.add_track(Track("edinburgh", "london", 4))
    b.add_track(Track("london", "amsterdam", 2))
    b.add_track(Track("london", "dieppe", 2))
    b.add_track(Track("dieppe", "paris", 1))
    b.add_track(Track("dieppe", "bruxelles", 2))
    b.add_track(Track("dieppe", "brest", 2))
    b.add_track(Track("brest", "paris", 3))
    b.add_track(Track("brest", "pamplona", 4))
    b.add_track(Track("bruxelles", "amsterdam", 1))
    b.add_track(Track("bruxelles", "frankfurt", 2))
    b.add_track(Track("bruxelles", "paris", 2))
    b.add_track(Track("amsterdam", "essen", 3))
    b.add_track(Track("amsterdam", "frankfurt", 2))
    b.add_track(Track("paris", "pamplona", 4))
    b.add_track(Track("paris", "marseille", 4))
    b.add_track(Track("paris", "zurich", 3))
    b.add_track(Track("paris", "frankfurt", 3))
    b.add_track(Track("pamplona", "madrid", 3))
    b.add_track(Track("madrid", "lisboa", 3))
    b.add_track(Track("cadiz", "lisboa", 2))
    b.add_track(Track("madrid", "cadiz", 3))
    b.add_track(Track("madrid", "barcelona", 2))
    b.add_track(Track("pamplona", "barcelona", 2))
    b.add_track(Track("pamplona", "marseille", 4))
    b.add_track(Track("barcelona", "marseille", 4))
    b.add_track(Track("zurich", "munchen", 2))
    b.add_track(Track("zurich", "venezia", 2))
    b.add_track(Track("zurich", "marseille", 2))
    b.add_track(Track("roma", "marseille", 4))
    b.add_track(Track("munchen", "frankfurt",2 ))
    b.add_track(Track("munchen", "venezia",2 ))
    b.add_track(Track("munchen", "wien",3 ))
    b.add_track(Track("berlin", "frankfurt",3))
    b.add_track(Track("berlin", "essen",2))
    b.add_track(Track("berlin", "danzig",4))
    b.add_track(Track("berlin", "warszawa",4))
    b.add_track(Track("berlin", "wien",3))
    b.add_track(Track("essen", "frankfurt", 2))
    b.add_track(Track("kobenhavn", "essen", 3))
    b.add_track(Track("kobenhavn", "stockholm", 3))
    b.add_track(Track("zagrab", "sarajevo",3))
    b.add_track(Track("zagrab", "venezia",2))
    b.add_track(Track("zagrab", "wien",2))
    b.add_track(Track("zagrab", "budapest",2))
    b.add_track(Track("venezia", "roma", 2))
    b.add_track(Track("budapest", "wien", 1))
    b.add_track(Track("budapest", "sarajevo", 3))
    b.add_track(Track("budapest", "bucuresti", 4))
    b.add_track(Track("budapest", "kyiv", 6))
    b.add_track(Track("wien", "warszawa", 4))
    b.add_track(Track("brindisi", "roma", 2))
    b.add_track(Track("brindisi", "palermo",3 ))
    b.add_track(Track("brindisi", "athina", 4))
    b.add_track(Track("roma", "palermo", 4))
    b.add_track(Track("palermo", "smyrna", 6))
    b.add_track(Track("athina", "sarajevo", 4))
    b.add_track(Track("athina", "sofia", 3))
    b.add_track(Track("athina", "smyrna", 2))
    b.add_track(Track("sofia", "sarajevo", 2))
    b.add_track(Track("sofia", "bucuresti", 2))
    b.add_track(Track("sofia", "constantinople", 3))
    b.add_track(Track("sevastopol", "bucuresti",4))
    b.add_track(Track("sevastopol", "rostov",4))
    b.add_track(Track("sevastopol", "sochi",2))
    b.add_track(Track("sevastopol", "erzurum",4))
    b.add_track(Track("sevastopol", "constantinople",4))
    b.add_track(Track("constantinople", "smyrna", 2))
    b.add_track(Track("constantinople", "angora", 2))
    b.add_track(Track("constantinople", "bucuresti", 3))
    b.add_track(Track("angora", "erzurum", 3))
    b.add_track(Track("angora", "smyrna", 3))
    b.add_track(Track("sochi", "rostov", 2))
    b.add_track(Track("sochi", "erzurum", 3))
    b.add_track(Track("kyiv", "warszawa", 4))
    b.add_track(Track("kyiv", "bucuresti", 4))
    b.add_track(Track("kyiv", "kharkov", 4))
    b.add_track(Track("kyiv", "smolensk", 3))
    b.add_track(Track("kyiv", "wilno", 2))
    b.add_track(Track("kharkov", "rostov", 2))
    b.add_track(Track("kharkov", "moskva", 4))
    b.add_track(Track("wilno", "warszawa",3))
    b.add_track(Track("wilno", "smolensk",3))
    b.add_track(Track("wilno", "riga",4))
    b.add_track(Track("wilno", "petrograd",4))
    b.add_track(Track("danzig", "warszawa", 2))
    b.add_track(Track("danzig", "riga", 3))
    b.add_track(Track("moskva", "petrograd", 4))
    b.add_track(Track("moskva", "smolensk", 2))
    b.add_track(Track("petrograd", "riga", 4))
    b.add_track(Track("petrograd", "stockholm", 8))
    b.add_mission(ConnectCitiesMission("amsterdam", "pamplona",7))
    b.add_mission(ConnectCitiesMission("amsterdam", "wilno",12))
    b.add_mission(ConnectCitiesMission("angora", "kharkov",10))
    b.add_mission(ConnectCitiesMission("athina", "angora",5))
    b.add_mission(ConnectCitiesMission("athina", "wilno",11))
    b.add_mission(ConnectCitiesMission("barcelona", "bruxelles",8))
    b.add_mission(ConnectCitiesMission("barcelona", "munchen",8))
    b.add_mission(ConnectCitiesMission("berlin", "bucuresti",8))
    b.add_mission(ConnectCitiesMission("berlin", "moskva",12))
    b.add_mission(ConnectCitiesMission("berlin", "roma",9))
    b.add_mission(ConnectCitiesMission("brest", "marseille",7))
    b.add_mission(ConnectCitiesMission("brest", "petrograd",20))
    b.add_mission(ConnectCitiesMission("brest", "venezia",8))
    b.add_mission(ConnectCitiesMission("bruxelles", "danzig",9))
    b.add_mission(ConnectCitiesMission("budapest", "sofia",5))
    b.add_mission(ConnectCitiesMission("cadiz", "stockholm",21))
    b.add_mission(ConnectCitiesMission("edinburgh", "athina",21))
    b.add_mission(ConnectCitiesMission("edinburgh", "paris",7))
    b.add_mission(ConnectCitiesMission("essen", "kyiv",10))
    b.add_mission(ConnectCitiesMission("frankfurt", "kobenhavn",5))
    b.add_mission(ConnectCitiesMission("frankfurt", "smolensk",13))
    b.add_mission(ConnectCitiesMission("kobenhavn", "erzurum",21))
    b.add_mission(ConnectCitiesMission("kyiv", "petrograd",6))
    b.add_mission(ConnectCitiesMission("kyiv", "sochi",8))
    b.add_mission(ConnectCitiesMission("lisboa", "danzig",20))
    b.add_mission(ConnectCitiesMission("london", "berlin",7))
    b.add_mission(ConnectCitiesMission("london", "wien",10))
    b.add_mission(ConnectCitiesMission("madrid", "dieppe",8))
    b.add_mission(ConnectCitiesMission("madrid", "zurich",8))
    b.add_mission(ConnectCitiesMission("marseille", "essen",8))
    b.add_mission(ConnectCitiesMission("palermo", "constantinople",8))
    b.add_mission(ConnectCitiesMission("palermo", "moskva",20))
    b.add_mission(ConnectCitiesMission("paris", "wien",8))
    b.add_mission(ConnectCitiesMission("paris", "zagrab",7))
    b.add_mission(ConnectCitiesMission("riga", "bucuresti",10))
    b.add_mission(ConnectCitiesMission("roma", "smyrna",8))
    b.add_mission(ConnectCitiesMission("rostov", "erzurum",5))
    b.add_mission(ConnectCitiesMission("sarajevo", "sevestopol",8))
    b.add_mission(ConnectCitiesMission("smolesk", "rostov",8))
    b.add_mission(ConnectCitiesMission("sofia", "smyrna",5))
    b.add_mission(ConnectCitiesMission("stockholm", "wien",11))
    b.add_mission(ConnectCitiesMission("venezia", "constantinople",10))
    b.add_mission(ConnectCitiesMission("warszawa", "smolensk",6))
    b.add_mission(ConnectCitiesMission("zagrab", "brindisi",6))
    b.add_mission(ConnectCitiesMission("zurich", "brindisi",6))
    b.add_mission(ConnectCitiesMission("zurich", "budapest",6))
    return b
